ALTER USER sys IDENTIFIED BY password;

ALTER SESSION SET CONTAINER = orclpdb1;

CREATE USER javatestapp_7263 IDENTIFIED BY password;

GRANT CREATE SESSION TO javatestapp_7263;

GRANT CREATE TABLE TO javatestapp_7263;

ALTER USER javatestapp_7263 QUOTA UNLIMITED ON USERS;

